name: Hikari
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_blue_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon1.png
    - assets/icon2.png
    - assets/icon3.png
    - assets/images/knee.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon1.png